# Generated by Django 2.2.12 on 2022-12-30 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('stok', models.IntegerField()),
                ('deskripsi', models.TextField(null=True)),
                ('foto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pinjambarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('tgl_mulai', models.DateField()),
                ('tgl_selsai', models.DateField()),
                ('lokasi_barang', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.Barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
